AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  actgan-lambda-service

  Serverless backend for serving ACTGAN generated images

Globals:
  Function:
    Timeout: 10

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"
  ActganGenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        GenerateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /generate
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./generate_function
      DockerTag: python3.9-v1
  ActganGetDatasetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_datasets_function/
      Handler: get_datasets.lambda_handler
      Runtime: python3.9
      Policies:
        - S3ReadPolicy:
            BucketName: actgan-models
      Environment:
        Variables:
          AWS_BUCKET_NAME: "actgan-models"
      Events:
        GetDatasetsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /get-datasets
            Method: get
    Architectures:
      - x86_64
    