AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  actgan-lambda-service

  Serverless backend for serving ACTGAN generated images

Globals:
  Function:
    Timeout: 10
    Environment:
      Variables:
        AWS_BUCKET_NAME: "actgan-models"

Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - "*~1*"
  ActganGenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      MemorySize: 512
      Policies:
        - S3ReadPolicy:
            BucketName: actgan-models
      Events:
        GenerateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /generate
            Method: get
            RequestParameters:
            - method.request.querystring.dataset:
                Caching: true
                Required: true
            - method.request.querystring.epoch:
                Caching: true
                Required: true
            - method.request.querystring.class_id:
                Caching: true
                Required: true
            - method.request.querystring.seed:
                Caching: true
                Required: true
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./generate_function
      DockerTag: python3.9-v1
  ActganGetDatasetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_datasets_function/
      Handler: get_datasets.lambda_handler
      Runtime: python3.9
      Policies:
        - S3ReadPolicy:
            BucketName: actgan-models
      Events:
        GetDatasetsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /get-datasets
            Method: get
  ActganGetClassesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_classes_function/
      Handler: get_classes.lambda_handler
      Runtime: python3.9
      Policies:
        - S3ReadPolicy:
            BucketName: actgan-models
      Events:
        GetClassesEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /get-classes
            Method: get
            RequestParameters:
              - method.request.querystring.dataset:
                  Caching: true
                  Required: true
  ActganGetEpochsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_epochs_function/
      Handler: get_epochs.lambda_handler
      Runtime: python3.9
      Policies:
        - S3ReadPolicy:
            BucketName: actgan-models
      Events:
        GetEpochsEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /get-epochs
            Method: get
            RequestParameters:
              - method.request.querystring.dataset:
                  Caching: true
                  Required: true
    Architectures:
      - x86_64
    